package com.example.fincorelite.shared.error;

public enum ErrorCode {
    COMMON_VALIDATION_FAILED,
    COMMON_MALFORMED_REQUEST,
    COMMON_TYPE_MISMATCH,
    COMMON_MISSING_PARAMETER,
    COMMON_RESOURCE_NOT_FOUND,
    COMMON_METHOD_NOT_ALLOWED,
    COMMON_UNSUPPORTED_MEDIA_TYPE,
    COMMON_DATA_CONFLICT,
    COMMON_CONCURRENT_MODIFICATION,
    COMMON_DATABASE_BUSY,
    COMMON_PERSISTENCE_INVARIANT_VIOLATED,
    COMMON_INTERNAL_ERROR,

    SYSTEM_METADATA_NOT_FOUND,
    SYSTEM_METADATA_ALREADY_EXISTS
}
